[functions.delete-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete-user/index.ts"

[functions.admin-purge-profile]
enabled = true
verify_jwt = false
entrypoint = "./functions/admin-purge-profile/index.ts"

[functions.tattoo-share]
enabled = true
verify_jwt = false
entrypoint = "./functions/tattoo-share/index.ts"
